### ISSUE TITLE
Token for Cck field of type select list is not getting replaced in paths

### ISSUE THREAD

**Issue by kausha** [md-systems/pathauto#100]
I have a cck field of type select list. And I am trying to use it in the patterns but in the url, it is not updating the pattern with the cck value. 
Pattern used - /[node:field_type_of_article]/[node:title]

**Comment by juampynr** [comment]
@kausha, could you update your Token module version to the latest development release and try again? This seems to me like a Token module issue rather than a Pathauto one.

**Comment by Berdir** [comment]
Yes. If you still can reproduce, please open a new issue on drupal.org.
