### ISSUE TITLE
Write an update path from 8.x-1.x to pattern-config-entities-simplified-ui

### ISSUE THREAD

**Issue by juampynr** [md-systems/pathauto#110]
Before we merge `pattern-config-entities-simplified-ui` on top of `8.x-1.x`, we need to write an update path so sites using `8.x-1.x` can update their databases to the new architecture.

**Comment by Berdir** [comment]
This shouldn't be too complicated. 

The logic more or less exists already, in PatternEditForm::buildEntity(). You need to loop over the existing config file for entity types/bundles/languages, maybe first create a simple array for each pattern you need to create, then create the pattern entities. You can use the same weight logic as there, additionally, you need to define a label and machine name, I'd suggest something like this:

Entity type [Bundle [Language]]: Content Article German, node_article_de

**Comment by juampynr** [comment]
Thanks for the tips @Berdir! I am on it.

**Comment by juampynr** [comment]
Work in progress at https://github.com/md-systems/pathauto/pull/111

**Comment by juampynr** [comment]
Fixed at https://github.com/md-systems/pathauto/pull/111#event-503358566
