### ISSUE TITLE
PHP Exception when enabling a language based pattern

### ISSUE THREAD

**Issue by juampynr** [md-systems/pathauto#112]
This issue was found while testing multilingual patterns at branch `pattern-config-entities-simplified-ui`.
## Steps to reproduce
1. Add a language such as French.
2. Enable content translation.
3. Create a pattern for Articles and French such as the following one:
   ![image](https://cloud.githubusercontent.com/assets/108130/12063360/e9511f02-afad-11e5-89f5-36dafa0d3c8c.png)
4. Open `node/add/article`. The following error appears:
   ![image](https://cloud.githubusercontent.com/assets/108130/12063362/fbd7f89e-afad-11e5-8478-9fbe90497dfc.png)

Here is what got logged:

```
[Thu Dec 31 11:03:10.952346 2015] [:error] [pid 6414] [client 127.0.0.1:40224] Uncaught PHP Exception Drupal\\Component\\Plugin\\Exception\\ContextException: "Required contexts without a value: language." at /var/www/drupal8/core/lib/Drupal/Core/Plugin/Context/ContextHandler.php line 117, referer: http://d8.local/node/add
```

**Comment by juampynr** [comment]
I am debugging what's happening.

**Comment by Berdir** [comment]
Yes, that has to be what I mentioned yesterday. As I said, ad the Contex thing and it should work. And no, it's not the same as what we have already.

**Comment by Berdir** [comment]
Also, we shoud put a try/catch around the relevant code. We must not break the site in case of a misconfigured pattern.

**Comment by juampynr** [comment]
@Berdir I added your suggestion at https://github.com/md-systems/pathauto/pull/111

**Comment by Berdir** [comment]
Ok. Can you open a separate PR to add a try/catch around the relevant code block _somewhere_. If for any reason alias generation fails, we want to log that as an error but not break the entity save.

I think we can close this now?
