### ISSUE TITLE
"pathauto-8.x-1.x-dev.tar.gz does not contain any .info.yml files."

### ISSUE THREAD

**Issue by turion** [md-systems/pathauto#114]
I just tried to install pathauto on my testing site from the link http://ftp.drupal.org/files/projects/pathauto-8.x-1.x-dev.tar.gz. I got this error:

pathauto-8.x-1.x-dev.tar.gz does not contain any .info.yml files.

**Comment by turion** [comment]
Ah. I'm starting to understand that you haven't actually pushed this to drupal.org. Sorry for the noise ;)

**Comment by juampynr** [comment]
Check out this branch. It has the latest working code: https://github.com/md-systems/pathauto/tree/pattern-config-entities-simplified-ui
