### ISSUE TITLE
Mismatched entity and/or field definitions after installing pathauto

### ISSUE THREAD

**Issue by flocondetoile** [md-systems/pathauto#117]
Hello,

Playing with pathauto after this comment https://www.drupal.org/node/2573683#comment-10710038 with  last dev versions of pathauto (from this repository) , token and ctools (from d.o).

After installing pathauto, I've got this error report in the dashboard.

Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.

Content
Delete field URL Alias.

Taxonomy term
Delete field URL Alias.

Pathauto seems to works fine with the first tests done. I don't know if this error is a false positive or reflect a real mismatch between field and database.

**Comment by Berdir** [comment]
I've noticed this too. We will look for a way to fix it, but don't worry, it's irrelevant, you can safely ignore it. The system sees a change in the definition for that field and thinks it has to do something, but not nothing really changed.

Drush provides a entity-updates command, you can run that to get rid of this.

**Comment by flocondetoile** [comment]
OK. thanks.

**Comment by Berdir** [comment]
https://www.drupal.org/node/2646784
