### ISSUE TITLE
Bulk Generate creation of Aliases gives ajax error

### ISSUE THREAD

**Issue by stewest** [md-systems/pathauto#120]
When I try to Bulk generate aliases, I get:

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /batch?id=277&op=do_nojs&op=do
StatusText: Internal Server Error
ResponseText: {}

An error occurred while processing Drupal\pathauto\Form\PathautoBulkUpdateForm::batchProcess with arguments : Drupal\pathauto\Form\PathautoBulkUpdateForm::batchProcess

I believe this is a known issue?

However, I may have a unique error in that I now see this:

InvalidArgumentException: The given alias pattern (/news/making-os-a-reality-first-stop-lower-main-road-25-may-2013-0) always matches the route view.taxonomy_term.page_3 in Drupal\pathauto\AliasUniquifier->isRoute() (line 174 of /var/www/openstreets_co_za/public_html/modules/contrib/pathauto/src/AliasUniquifier.php).

My version: 
PathAuto 8.x-1.x-dev
Token 8.x-1.0-alpha1

**Comment by juampynr** [comment]
Sounds like some of your patterns is returning duplicates aliases and therefore they are not created. Does that make any sense to you @stewest?

**Comment by Berdir** [comment]
See https://github.com/md-systems/pathauto/issues/62. The exception you get is the stop-gap I added to prevent an infinite loop. You seem to have a conflict with an existing route an aliases. I 'm not sure exactly how to properly solve this.

**Comment by stewest** [comment]
Hi. You're correct. It was a pattern that was duplicated accidentally by a view path expecting an argument where the [node:title] should have been. I changed that and then the Ajax error disappeared but no url-aliases were generated. My issue extends to here (but made a work around: https://github.com/md-systems/pathauto/issues/121#issuecomment-169248735

Thanks!

**Comment by Berdir** [comment]
There's still the related issue open, but we're moving back to drupal.org, so closing remaining issues here.
