### ISSUE TITLE
Make pathauto_entity_base_field_info() configurable

### ISSUE THREAD

**Issue by juampynr** [md-systems/pathauto#124]
This is a follow up for https://github.com/md-systems/pathauto/pull/115#issuecomment-168297315. After fixing it @Berdir said the following:

> Expose a list of checkboxes for each type. Ticking the checkbox should expose that base field for the selected entity types. In case a base field already exists and is not defined by us (e.g. node), it should be checked by default and be disabled. This in turn will then automatically expose a alias type plugin. At this point, we'll have achieved the goal of fully generic and automated integration with any entity type.

**Comment by Berdir** [comment]
https://www.drupal.org/node/2655780
