### ISSUE TITLE
"The service "pathauto.generator" has a dependency on a non-existent service "token.entity_mapper"

### ISSUE THREAD

**Issue by finnlewis** [md-systems/pathauto#128]
I just installed a fresh copy of Drupal 8.0.2 with Ctools 8.x-3.0-alpha21 and Token 8.x-1.0-alpha1.
When enabling Pathauto I get 
"The website encountered an unexpected error. Please try again later."
with the following in the logs:

Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The service "pathauto.generator" has a dependency on a non-existent service "token.entity_mapper"." at .....web/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php line 58

After refreshing and hitting /admin/config/search/path/ there are no tabs for patterns, settings, etc. so it looks like the error prevented the installation.

**Comment by rackberg** [comment]
I forked this project to fix this and created a pull request: https://github.com/md-systems/pathauto/pull/129

**Comment by Berdir** [comment]
Yes, you need dev versions of both token and ctools. There will likely be new alpha version of both soon after which this problem will disappear. I'm not sure if it's worth to change the composer.json until then. It's not even alpha yet, after all.

**Comment by rackberg** [comment]
I've done another commit to ensure that drupal/ctools will be available too.

**Comment by mihaimaftei** [comment]
Hello,

I am still getting this error when upgrading Drupal to 8.5.1 from 8.4.3.

I have the latest pathauto version(8.x-1.1)

**Comment by Berdir** [comment]
But you apparently have a *very* old token module version, which is the problem here.

**Comment by mihaimaftei** [comment]
This is the token version I am using "8.x-1.1+7-dev".
