### ISSUE TITLE
Autogenerated path incorrect for specific page

### ISSUE THREAD

**Issue by pjcarly** [md-systems/pathauto#131]
All of this is for Drupal 8 (not sure if this repo is only for D8)

Say you have a Basic page called Contact with the default language english, and a path pattern [node:title]

When I auto generate the path url alias, I should get: mydomain.com/contact right? however, for some reason the autogeneration always generates mydomain.com/contact-0, while working as expected on other pages.

**Comment by pjcarly** [comment]
Turns out, after some extra investigation, I think it has to do with the default Contact module in core, which generates an automatic URL alias for a contact form. I can't find a way to change that url alias though.

**Comment by Berdir** [comment]
It's not an alias, it's a route. You can't change that. Pathauto tries to not create aliases that prevent you from accessing those routes.

**Comment by pjcarly** [comment]
Darn, that is what I was afraid of, you reckon that the Contact module could make the route configurable so it wouldn't conflict?

**Comment by Berdir** [comment]
Unlikely, but that would have to happen in core.

It should still be possible to create a manual alias if you really want to have it I guess. Although it would be problematic for the actual /contact path.
