### ISSUE TITLE
Undefined method: Drupal\Core\Render\MetadataBubblingUrlGenerator::generateFromPath()

### ISSUE THREAD

**Issue by sebastianwestberg** [md-systems/pathauto#132]
First of all, thanks for for this great module.

I'm hitting the following error with Pathauto 8.x-1.x on Drupal 8.0.2 and Token 8.x-1.0-alpha1:
`Fatal error: Call to undefined method Drupal\Core\Render\MetadataBubblingUrlGenerator::generateFromPath() in /var/www/drupal/modules/pathauto/src/Form/PathautoSettingsForm.php on line 89``

Page where it shows: admin/config/search/path/settings
Do you have any idea what may cause this? Thanks in advance.

**Comment by Berdir** [comment]
I don't know what version you are using, but this method call was removed 4 month ago in e850af1.
