### ISSUE TITLE
D8 Beta 4: Pathauto: Fatal error: Call to undefined function Drupal\pathauto\Form\form_state_values_clean()

### ISSUE THREAD

**Issue by sachbearbeiter** [md-systems/pathauto#23]
D8 Beta 4: http://xxx.com/admin/config/search/path/settings

-> "Save configuration" -> Fatal error: Call to undefined function Drupal\pathauto\Form\form_state_values_clean() in /xxx/modules/contrib/pathauto/src/Form/PathautoSettingsForm.php on line 174

regards sb

**Comment by alex-mccabe** [comment]
It looks like this isn't happening anymore - I was able to save the form successfully, and I don't see any calls to form_state_values_clean in the pathauto code.

**Comment by Berdir** [comment]
Yes, this is definitely no longer an issue :)
