### ISSUE TITLE
D8 Beta 4: Pathauto: Delete aliases: General system error

### ISSUE THREAD

**Issue by sachbearbeiter** [md-systems/pathauto#24]
D8 Beta 4: http://d8.online-educa.com/admin/config/search/path/delete_bulk

Call of url: "Error
The website has encountered an error. Please try again later. "

regards sb

**Comment by sachbearbeiter** [comment]
Log:
"RuntimeException: An invalid implementation node_path_alias_types was added by hook_module_implements_alter() in Drupal\Core\Extension\ModuleHandler->buildImplementationInfo() (line 586 of /www/htdocs/w00a3c73/cms8/core/lib/Drupal/Core/Extension/ModuleHandler.php)."

**Comment by tanarurkerem** [comment]
#27 resolve this issue
