### ISSUE TITLE
Support custom/other entities

### ISSUE THREAD

**Issue by attiks** [md-systems/pathauto#41]
Are there plans to add support for all entities?

Drupal 7 has https://www.drupal.org/project/pathauto_entity

**Comment by Berdir** [comment]
If people are interested to work on it, sure. A lot of the internal code is already generic, the only thing that's required is a plugin implementation. We're working on making more code in there generic, but there are are a few things that need to be set _somehow_, like source path prefix for things like mass-delete. That could also be powered by a configuration form that generates plugin derivatives or something.

We're also working on going _beyond_ entities and better support things like that, by making the configuration and configuration forms fully controlled by plugins. First step is supporting config entities, as an example.

Start creating PR requests, preferably small step-by-step improvements :)

**Comment by attiks** [comment]
I created an issue in the pathauto_entity module https://www.drupal.org/node/2496701

**Comment by Berdir** [comment]
This would be a good place to complete the first todo listed in #115, make the base field configurable, then this should be fully supported.

**Comment by Berdir** [comment]
https://www.drupal.org/node/2655780
