### ISSUE TITLE
Pathauto as profile dependency won't install.

### ISSUE THREAD

**Issue by mglaman** [md-systems/pathauto#42]
PathautoManager.php is causing  'Route "entity.user.canonical" does not exist.' to throw on install with a profile which uses Pathauto. Haven't investigated why, yet.

**Comment by josereyero** [comment]
The easy workaround is to rebuild the routes before creating / updating any content in you profile_install()

\Drupal::service('router.builder')->rebuild();

**Comment by benjy** [comment]
I had a similar issue for files, simply putting pathauto after file_entity in the install profile dependency list was enough to mitigate the issue for now.

**Comment by Berdir** [comment]
Is this still an issue? If so, please open a new issue on drupal.org.
