### ISSUE TITLE
Aliases always change on entity save

### ISSUE THREAD

**Issue by DuaelFr** [md-systems/pathauto#47]
During the entity path generation, the call to AliasUniquifier::uniquify() always changes the alias, even if it should not (resaving an existing entity without changing anything for example).

That is cause by a AliasUniquifier::isRoute() method failure. The fact is that the UrlMatcher always find a route to the alias because it converts the alias into a Request that properly points to the canonical entity route. The problem is that the match() method only returns a boolean so we cannot ensure that the matching route is not already the route to the given source.

I have no idea on how to fix that particular issue.

**Comment by Berdir** [comment]
Hm. Not sure I fully understand what the problem is.

Is there a way we can write a test for this?

**Comment by DuaelFr** [comment]
Steps to reproduce:
1. enable pathauto
2. create a node with title "Foo", the alias should be "/content/foo"
3. edit the node and save it unchanged, the alias is now "/content/foo-0"

I'll try to write a test for this issue today.

**Comment by DuaelFr** [comment]
Confirmed. Thanks!
