### ISSUE TITLE
Bring back the custom path checkbox

### ISSUE THREAD

**Issue by DuaelFr** [md-systems/pathauto#59]
Sometimes we need to define a custom path for our content. In the D7 version we had a checkbox to disable pathauto for a given node. In the D8 version, as this checkbox disappeared, there is no way to define a custom path for out content.

Is it just something that have not been ported yet or was there another reason to remove that checkbox?

**Comment by Berdir** [comment]
This works fine if you use the pathauto widget for the alias field on the manage form page.

It's used automatically for new form displays, but existing ones aren't updated. We could write some code in _install() to do this I guess.

**Comment by DuaelFr** [comment]
If you don't, you should plan to add these instructions in the readme.
Thank you for the quick answer anyway ;)

**Comment by Berdir** [comment]
Pull requests for either are very welcome :)

**Comment by pedrorocha-net** [comment]
Is there any problem in keep the behaviour people were used to on previous version? Any drawbacks on doing that?

**Comment by Berdir** [comment]
The behavior is the same, you just need to configure the widget. We need to document that as I said. We could try to update existing configuration but that's always tricky.

**Comment by pedrorocha-net** [comment]
Oh, I didn't understood right the first time I read the comments above regarding the widget. I'll update README file.

Thanks
