### ISSUE TITLE
Existing route check is problematic

### ISSUE THREAD

**Issue by Berdir** [md-systems/pathauto#62]
The alias unique service has a check to see if an alias matches an existing route.

That alone is fine. But the problem is that the alias manager then just retries with -0, which in most cases, matches the route again. Then -1, and so on.

This results in an endless loop.

5bca622 is a workaround that at least throws an exception. But I'm not sure if the route check like this is actually correct and should be there. That should possibly be checked separately and a match should just abort.

**Comment by stewest** [comment]
You are correct, thank you. I only figured it out later, when I saw a more specific url, and deciphered it meaning. All sorted now on my side.

**Comment by Berdir** [comment]
This is handled in https://www.drupal.org/node/2655874
