### ISSUE TITLE
Cannot install after failed installation

### ISSUE THREAD

**Issue by pglatz** [md-systems/pathauto#63]
I'm using D8 beta 14, and was happty to learn of this project. I installed it and the token module from https://github.com/larowlan/token but token had a few problems with their calls to checkPlain. I found a fix for this and posted it to their issue queue, but when I went back to pathauto, I couldn't install it, am getting: "Unable to install Pathauto, pathauto.pattern, pathauto.settings already exist in active configuration."

I'm new to Drupal 8, and am not sure how to fix this. Is it a possible issue with the module, or something more general?

**Comment by Berdir** [comment]
Looks like something went wrong with the installation, you will need to delete that configuration manually, e.g. with drush or a config export/import.

More importantly, you are using the wrong token version, token is back on drupal.org.

**Comment by cvanderlinden** [comment]
How do you delete the configuration with drush?
