### ISSUE TITLE
Pathauto breaks PATCH requests via REST

### ISSUE THREAD

**Issue by mortenson** [md-systems/pathauto#64]
With Pathauto enabled, every PATCH request to `/node/*` results in the following HTTP 500 error:

```
Uncaught PHP Exception LogicException: "The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\\rest\\ResourceResponse."
```

GET requests seem to work fine, have not tried POST requests yet. Is Pathauto doing early rendering or adding cache metadata to responses anywhere?

**Comment by Berdir** [comment]
It's probably the token calls that are happening there.

Just doesn't make sense to bother about stuff like that...

Will leave Wim Leers a tell about this.

**Comment by wimleers** [comment]
> It's probably the token calls that are happening there.

Just like in `file_entity` — that sounds plausible.

> Just doesn't make sense to bother about stuff like that...

What do you mean? `pathauto` doesn't care about cacheability. So it needs to tell `Token::replace()` that. It needs to explicitly opt out.

**Comment by Berdir** [comment]
What I mean is that throwing an exception for something like this IMHO way too strict. For starts, we really shouldn't bother with this on non-GET/HEAD requests, they are by definition not cacheable, so why worry about cacheability?

Second, we actually have all the information we need, this could maybe be an assert or some optional logging. Which then also should provide as much information as possible what kind of metadata was found, so you know what to look for.

**Comment by mortenson** [comment]
POST and PATCH both return an empty Drupal\rest\ResourceResponse, which implements Drupal\Core\Cache\CacheableResponseInterface. If we went forward with patching core, we would need to instead return a generic Symfony\Component\HttpFoundation\Response. 

I would still be interested to know what needs to change in Pathauto to prevent this, regardless of the path we take.

**Comment by wimleers** [comment]
> For starts, we really shouldn't bother with this on non-GET/HEAD requests, they are by definition not cacheable, so why worry about cacheability?

The overall response is indeed not cacheable, but parts of the response _may_ be cacheable. However, the main content should then still be generated dynamically, so … I think you're right that we should actually not check GET/HEAD requests in `\Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber`.

---

> I would still be interested to know what needs to change in Pathauto to prevent this, regardless of the path we take.

`Token::replace()`'s signature is:

```
public function replace($text, array $data = array(), array $options = array(), BubbleableMetadata $bubbleable_metadata = NULL) {
```

So you need to update:

```
Token::replace($text, ['node' => $node], [])
```

to:

```
Token::replace($text, ['node' => $node], [], new BubbleableMetadata())
```

In the case of Pathauto, you would simply not do anything with that bubbleable metadata object.

**Comment by Berdir** [comment]
>  I think you're right that we should actually not check GET/HEAD requests in

I guess you meant non-GET/HEAD requests? :)

**Comment by mortenson** [comment]
Created #65 based on @wimleers response, which fixes this issue.

**Comment by drupol** [comment]
I also encountered the same error for the Language Selection Page module when used with Metatag.

I've created the issue on the Metatag issue queue: https://github.com/damienmckenna/metatag/pull/6

Thanks @wimleers !
