### ISSUE TITLE
Visiting a user edit page results in fatal error

### ISSUE THREAD

**Issue by tanc** [md-systems/pathauto#66]
Trying to edit a user at, for example, user/1/edit, results in a fatal error:

`Fatal error: Call to a member function addCacheableDependency() on a non-object in /var/www/core/lib/Drupal/Core/Utility/Token.php on line 307`

This is on beta14 with latest master of pathauto. Let me know if you need more details.

**Comment by Berdir** [comment]
Can't reproduce, you probably had a conflicting combination of core/token/pathauto.
