### ISSUE TITLE
Use entity info for batchUpdate method

### ISSUE THREAD

**Issue by ghost** [md-systems/pathauto#67]
I see that each entity alias plugin implements batchUpdate method. It looks to me like this could be easily avoided by using entity info for table names and entity keys and have one method in the base class. There is the sourcePrefix method which will make this easy but I also think using canonical link form the entity info would be a better idea.

**Comment by Berdir** [comment]
Yes, we can do that, we just didn't get there yet. Pull requests welcome.

We could try to standardize the prefix method too, but the canonical link is not the same. but we can try to remove the placeholder dynamically in a default implementation.

**Comment by ghost** [comment]
I'm just playing with pathauto after a while so I came up with something like 

```
/**
   * {@inheritdoc}
   */
  public function getSourcePrefix() {
    $entity_info = \Drupal::entityManager()->getDefinition($this->getPluginId());
    $path = $entity_info->getLinkTemplate('canonical');
    return ltrim(str_replace('{' . $entity_info->id() . '}', '', $path), '/');
  }
```

Although the plugin ID does not necessarily has to be entity id and also the link can have something appended after the entity id but plugins can provide whatever they want so this is very generic default value.

**Comment by Berdir** [comment]
Again, please create pull requests instead of posting code snippets in issues. Nothing will happen with this (and separate PR's for the two things mentioned here).

**Comment by Berdir** [comment]
https://github.com/md-systems/pathauto/pull/85
