### ISSUE TITLE
AliasTypeInterface is missing ContainerFactoryPluginInterface dependency

### ISSUE THREAD

**Issue by ghost** [md-systems/pathauto#68]
Without extending the ContainerFactoryPluginInterface the language and entity managers won't be available in EntityAliasTypeBase.

**Comment by juampynr** [comment]
https://github.com/md-systems/pathauto/blob/pattern-config-entities-simplified-ui/src/Plugin/pathauto/AliasType/EntityAliasTypeBase.php and https://github.com/md-systems/pathauto/blob/pattern-config-entities-simplified-ui/src/Plugin/pathauto/AliasType/ForumAliasType.php do implement this interface. Should we move it up there? If so, why?

**Comment by Berdir** [comment]
Any plugin that needs this can do this itself, and the base class includes it too. No need for this to be on the interface, closing.
