### ISSUE TITLE
EntityAliasTypeBase::defaultConfiguration should provide keyed array

### ISSUE THREAD

**Issue by ghost** [md-systems/pathauto#69]
The default configuration should at least provide keyed array with null values so there's some guidance even though the 'default' key will be overridden by plugins, it should be present nevertheless.

**Comment by juampynr** [comment]
This method is gone at the branch with the latest code: https://github.com/md-systems/pathauto/tree/pattern-config-entities-simplified-ui

Should we close this issue or is it still valid?

**Comment by Berdir** [comment]
This happened now, so closing this. There is no default config anymore.
