### ISSUE TITLE
Pathauto should not ship with patterns

### ISSUE THREAD

**Issue by ghost** [md-systems/pathauto#70]
Since the data from pathauto.patterns.yml is the same that is provided by the default alais plugins it is redundant and it should not ship with the module or it should be an empty array.

**Comment by juampynr** [comment]
https://github.com/md-systems/pathauto/blob/8.x-1.x/config/install/pathauto.pattern.yml is gone in the branch with the latest version of the module's code (https://github.com/md-systems/pathauto/tree/pattern-config-entities-simplified-ui).

Shall we close this issue?

**Comment by Berdir** [comment]
This happened now, so closing this. There is no default config anymore.
