### ISSUE TITLE
Default key in defaultConfiguration for Alias plugins should be string and not array

### ISSUE THREAD

**Issue by ghost** [md-systems/pathauto#71]
According to pathauto.pattern mapping the 'patterns.default' key is a string and not an array but all core plugins provide this as an array:

```
public function defaultConfiguration() {
  return array('default' => array('/[term:vocabulary]/[term:name]')) + parent::defaultConfiguration();
}
```

instead of

```
public function defaultConfiguration() {
  return array('default' => '/[term:vocabulary]/[term:name]') + parent::defaultConfiguration();
}
```

**Comment by Berdir** [comment]
Provide pull requests, not just issues. It's easy enough and nothing will happen unless you (or someone else) does it.

**Comment by juampynr** [comment]
This method is gone at https://github.com/md-systems/pathauto/tree/pattern-config-entities-simplified-ui.

Shall we close it?

**Comment by Berdir** [comment]
I'm waiting for that branch to be merged into 8.x-1.x before closing this and the related issues. But yes, we can do so once that happened.

**Comment by Berdir** [comment]
This happened now, so closing this. There is no default config anymore.
