### ISSUE TITLE
Illegal offset type line 265 in PathautoManager.php

### ISSUE THREAD

**Issue by sebastianwestberg** [md-systems/pathauto#73]
I receive the following error when I create a new node and hit the save button:
`Warning: Illegal offset type in Drupal\pathauto\PathautoManager->cleanString() (line 265 of modules/pathauto/src/PathautoManager.php).``

Here's the whole stack trace if it helps:
`Drupal\pathauto\PathautoManager->cleanString(Object, Array)
Drupal\pathauto\PathautoManager->cleanTokenValues(Array, Array, Array, Object)
Drupal\Core\Utility\Token->replace('/[node:field_type]/[node:title]', Array, Array)
Drupal\pathauto\PathautoManager->createAlias('node', 'insert', '/node/30', Array, 'product', 'en')
Drupal\pathauto\PathautoManager->updateAlias(Object, 'insert')
pathauto_entity_insert(Object)
call_user_func_array('pathauto_entity_insert', Array)
Drupal\Core\Extension\ModuleHandler->invokeAll('entity_insert', Array)
Drupal\Core\Entity\EntityStorageBase->invokeHook('insert', Object)
Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('insert', Object)
Drupal\Core\Entity\EntityStorageBase->doPostSave(Object, )
Drupal\Core\Entity\ContentEntityStorageBase->doPostSave(Object, )
Drupal\Core\Entity\EntityStorageBase->save(Object)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object)
Drupal\Core\Entity\Entity->save()
Drupal\node\NodeForm->save(Array, Object)
call_user_func_array(Array, Array)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object)
Drupal\Core\Form\FormBuilder->processForm('node_product_form', Array, Object)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object)
Drupal\Core\Entity\EntityFormBuilder->getForm(Object)
Drupal\node\Controller\NodeController->add(Object)
call_user_func_array(Array, Array)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1)
Drupal\devel\StackMiddleware\DevelMiddleware->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1)
Stack\StackedHttpKernel->handle(Object, 1, 1)
Drupal\Core\DrupalKernel->handle(Object)`

**Comment by Berdir** [comment]
Sounds like you have a wrong token implementation that returns an object instead of a string. Also, you seem to be not using the latest version, my line 256 is empty.

**Comment by sebastianwestberg** [comment]
@Berdir Thanks for your response. What implementation of token do you suggest? Also, the line should be "265" and not 256.

**Comment by sebastianwestberg** [comment]
@Berdir Sorry to bother you, but I feel like I need to add some more information to this issue which I hope can be helpful.

To reproduce the error, create a new Vocabulary and add a term to that. On a content type you have to create a field that references this vocabulary (let's call it field_content_tax). 

From pathauto pattern settings you add the field for the previously selected content type so it looks something like this: `/[node:field_content_tax]/[node:title]`

Create a new node with the affected content type and select a term from the referenced vocabulary and hit save. The error referenced in my first post is shown.

**Comment by Berdir** [comment]
We're doing things like that with beta 15 and it works fine. 

As I said, the error sounds like a bug in a token implementation, but I assume you're using standard token.module. This is likely not a bug in Pathauto but whatever feeds data to it. Check your formatter configuration for the token view mode. 

Try writing a test for it.
