### ISSUE TITLE
Override path on particular items is not allowed for nodes (and maybe other types, as it was on D7)

### ISSUE THREAD

**Issue by pedrorocha-net** [md-systems/pathauto#77]
On "URL path settings" field, we had a checkbox on D7 to say if this particular content should comply with the pattern or have a manually created path. Right now, on D8, the checkbox is not there, but we are allowed to specify the path, that causes confusion as even if you set a path manually, the pattern will be applied and ignore your manual input.

I reported this first on https://www.drupal.org/node/2574701, but from the discussion on https://www.drupal.org/node/2573683, i'm moving here.

**Comment by Berdir** [comment]
See https://github.com/md-systems/pathauto/issues/59.
