### ISSUE TITLE
Documentation: README.md references missing .txt files

### ISSUE THREAD

**Issue by lucyllewy** [md-systems/pathauto#79]
The README.md file references INSTALL.txt, API.txt and CHANGELOG.txt. All three of these files appear to be non-existent in the repository.

**Comment by vizo** [comment]
:+1:

**Comment by juampynr** [comment]
Pull request at https://github.com/md-systems/pathauto/pull/106

**Comment by juampynr** [comment]
@Berdir, shall we close this issue?

**Comment by Berdir** [comment]
Yes.
