### ISSUE TITLE
Minimal upgrade path

### ISSUE THREAD

**Issue by DuaelFr** [md-systems/pathauto#87]
After upgrading the module to the latests dev version I get this error while running drush updb or when I try to add a field on an existing content type.

Failed: Drupal\Component\Plugin\Exception\PluginNotFoundException: The "pathauto" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 57 of
core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

That error has been introduced by the change made in 13f6aa8ae01a6769921636d75ff1b81f69223ca6 where the pathauto plugin has been removed. The problem is that existing nodes/entities still have this setting saved somewhere (but not in the config yml files).

I'm trying to fix that in a hook_update_N 

``` php
function mymodule_update_8004() {
  // Replace values in the 'entity.definitions.installed' keyvalue collection.
  $collection = \Drupal::service('keyvalue')->get('entity.definitions.installed');
  foreach ($collection->getAll() as $value_name => $value) {
    if (!is_array($value) || empty($value['path'])) {
      continue;
    }

    // Retrieve and change path base field definition.
    $path_definition = $value['path'];
    $options = $path_definition->getDisplayOptions('form');
    $options['type'] = 'path';
    $path_definition->setDisplayOptions('form', $options);

    // Save the new value.
    $collection->set($value_name, $path_definition);
  }

  // Replace values in the content types config.
  $configFactory = \Drupal::configFactory();
  $node_types = \Drupal\node\Entity\NodeType::loadMultiple();
  foreach ($node_types as $type_name => $node_type) {
    $config = $configFactory->getEditable('core.entity_form_display.node.' . $type_name . '.default');
    $config->set('content.path.type', 'path');
    $config->save();
  }
}
```

but I still get some errors like:

Drupal\Core\Entity\EntityStorageException: Exception thrown while performing a schema update. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException() (line 1459 of
core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

I'm stuck there, any help would be highly appreciated :/

**Comment by DuaelFr** [comment]
EclipseGc tried to help me on IRC but the only solution we found was to revert then uninstall then update then reinstall.
It's not perfectly working but it's good enough to be able to move forward.

**Comment by Berdir** [comment]
Create a PR, not an issue, that's much easier to discuss the code.

> $config = $configFactory->getEditable('core.entity_form_display.node.' . $type_name . '.default');

getEditable() always gives you an object, also if it didn't exist before. There could possibly also be multiple form modes and non-node form displays that need it, e.g. users or terms.

You want to do an entity query instead or just load all form display config entities and loop over those.

Also, the path field could theoretically also be called something else, to be sure, you need to check for the type, not the name of the field.

**Comment by DuaelFr** [comment]
Thank you for your answer. I finally did what EclipseGc suggested: reverted then uninstalled then re-updated then reinstalled. Please don't change you mind about that widget anymore ;)

**Comment by Berdir** [comment]
Yeah, I read that. But I'll need to update my sites too so I and probably others will need a solution, keeping this open for now.

**Comment by Berdir** [comment]
I now committed a pathauto_update_8001() function, based on your code and my suggestions. Thanks for providing this.

**Comment by DuaelFr** [comment]
Thank you :)
