### ISSUE TITLE
A new translation of an existing node has "Generate automatic URL alias" unchecked by default.

### ISSUE THREAD

**Issue by paul-mckibben** [md-systems/pathauto#90]
Setup: Drupal 8.0.0-rc2 with the latest 8.x-1.x branch of pathauto. Content Translation is enabled.

To reproduce: 
- Using a content type that has a URL alias pattern specified, create a new node.
- Note that the "Generate automatic URL alias" checkbox is checked.
- Save and publish the node with automatic alias.
- Create a new translation of the node.
- Note that the "Generate automatic URL alias" checkbox is unchecked.

Expected behavior: when creating a new translation of a node whose content type has a URL alias pattern specified, the "Generate automatic URL alias" checkbox should be checked.

**Comment by paul-mckibben** [comment]
The problem may be a core issue, but I'm not sure. I was trying to fix this locally, but I cannot find a way to determine if an entity translation "is new."

The affected PathAuto code seems to be in PathautoWidget.php, method formElement():

```
    if (!isset($entity->path->pathauto)) {
      if (!$entity->isNew()) {
        module_load_include('inc', 'pathauto');
        $path = \Drupal::service('path.alias_manager')->getAliasByPath('/' . $entity->urlInfo()->getInternalPath(), $entity->language()->getId());
        $pathauto_alias = \Drupal::service('pathauto.manager')->createAlias($entity->getEntityTypeId(), 'return', '/' . $entity->urlInfo()->getInternalPath(), array($entity->getEntityType()->id() => $entity), $entity->bundle(), $entity->language()->getId());
        $entity->path->pathauto = ($path != '/' . $entity->urlInfo()->getInternalPath() && $path == $pathauto_alias);
      }
      else {
        $entity->path->pathauto = TRUE;
      }
    }
```

The problem is that $entity->isNew() returns FALSE for any new translation of an existing entity. Furthermore, I can't find any other way to tell if a translation is new, even if an entity is not new.

**Comment by Berdir** [comment]
Tricky.

I'll try to ask plach. So far, the only thing I've seen is in ContentEntityStorageBase::invokeTranslationHooks(), it invokes a hook for new translations and to find them, it compares it with the original entity. So we could do something similar if there's really no other way.

**Comment by plach79** [comment]
This seems to be something related to https://www.drupal.org/node/2382675, which I was about to start working on. See you there :)

**Comment by plach79** [comment]
This should address the issue above https://www.drupal.org/node/2382675#comment-10552060

**Comment by Berdir** [comment]
I've just merged in https://github.com/md-systems/pathauto/pull/82. That implicitly fixed this problem because we now store a flag per node whether we should create an alias automatically or not.

Right now, that state is the same for all translations, which is not very clear from the UI right now. So I'm wondering if we should store that flag per translation. Even then, I think it would now work because we apply a default value to create an alias, that is also called for a new translation.

**Comment by Berdir** [comment]
Closing this, we'll discuss the second part in a new issue.

**Comment by joejoseph00** [comment]
I've come accross a similar need, documented our solution here: 
https://www.drupal.org/node/2030983#comment-11992561
